begin;
select plan(18);
select has_table('public','wa_organizations','organizations table exists');
select has_table('public','wa_teams','teams table exists');
select has_table('public','wa_conversations','conversations table exists');
select has_table('public','wa_messages','messages table exists');
select has_table('public','wa_ai_runs','ai runs table exists');
select has_table('public','wa_audit_log','audit table exists');
select has_view('public','wa_my_profile','profile view exists');
select has_view('public','wa_inbox','inbox view exists');
select has_view('public','wa_agent_workload','workload view exists');
select has_view('public','wa_team_directory','team directory view exists');
select has_function('public','wa_ingest_inbound_message',array['uuid','uuid','text','text','text','text','text','text','timestamp with time zone','jsonb'],'ingest function exists');
select has_function('public','wa_update_delivery_status',array['text','text','jsonb','timestamp with time zone'],'status function exists');
select has_function('public','wa_claim_ai_run',array['uuid'],'ai claim exists');
select has_function('public','wa_handover_conversation',array['uuid','text','text','text','text','numeric'],'handover exists');
select has_function('public','wa_assign_conversation',array['uuid','uuid'],'assignment exists');
select has_function('public','wa_resolve_conversation',array['uuid'],'resolve exists');
select ok(not has_function_privilege('anon','public.wa_ingest_inbound_message(uuid,uuid,text,text,text,text,text,text,timestamptz,jsonb)','EXECUTE') and not has_function_privilege('authenticated','public.wa_ingest_inbound_message(uuid,uuid,text,text,text,text,text,text,timestamptz,jsonb)','EXECUTE'),'ingest is service-only');
select ok(not has_function_privilege('anon','public.wa_claim_ai_run(uuid)','EXECUTE') and not has_function_privilege('authenticated','public.wa_claim_ai_run(uuid)','EXECUTE'),'ai claim is service-only');
select * from finish();
rollback;
